### ISSUE TITLE
Create database

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#10]
It should be a local MongoDB setup

**Comment by js-kyle** [comment]
Should we use Mongoose ODM or the Mongo driver directly? I would assume Mongoose

**Comment by DeFlanko** [comment]
I just watched a few youtube videos on MongoDB and im curious. Where do you see the need in UMS for a DB? The indexing part? Storing Metadata for each indexed movie locally?

**Comment by SubJunk** [comment]
@DeFlanko cool to see you here :) this is for a new subproject of UMS, `api`, and it is basically a permanent cache for OpenSubtitles. This won't exist locally for users, but the UMS "client" will send requests to this API instead of directly to OpenSubtitles

**Comment by SubJunk** [comment]
This is done now
