### ISSUE TITLE
Decide whether to use Node 14

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#112]
Node 14 got released and has some nice things like improved performance and the optional chaining feature. We could wait until it hits LTS in October or be early adopters. Thoughts?

**Comment by js-kyle** [comment]
It's still active LTS so I'm keen to use it. Easy enough to rollback if there are issues

**Comment by js-kyle** [comment]
it passed CI with no new deprecation warnings

**Comment by SubJunk** [comment]
Sweet I'll merge it when I have time to update it on the server too

**Comment by SubJunk** [comment]
We're running that now
