### ISSUE TITLE
Search by title should merge results with OpenSubtitles

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#118]
At the moment it only returns from IMDb, but we should attempt to hydrate the data with OpenSubtitles too. The code is already mostly there but unreachable

**Comment by js-kyle** [comment]
I'm not sure on this one, OpenSubtitles doesnt seem to provide an accurate enough way to do this. The subtitles function doesn't seem to return the data that we want

**Comment by SubJunk** [comment]
Fair enough. I think we have some other things to try anyway so I'll close this for now
