### ISSUE TITLE
Localization test broken

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#1196]
@SurfaceS it looks like the localization feature has broken, or the test has (it could be that the TMDB data got changed?), are you still around to look into it? Please let me know so I know whether I need to fix this

```
    Expected: "La clé de l’avenir est enfin découverte."
    Received: "The key to the future is finally unearthed."
```

**Comment by SubJunk** [comment]
Seems to have resolved itself, might have been a TMDB blip

**Comment by Mik-S-UMS** [comment]
I'm not sure this is relevant but there is a user on the [forum ](https://www.universalmediaserver.com/forum/viewtopic.php?t=15579)that is unable to get any metadata from the API, 
It keeps returning the error 
`API status was 404 for {"error":"Metadata not found."}`
Only thing I can think of is a localization problem as it does seem to work on English shows.

**Comment by SubJunk** [comment]
It happened again for some different data so I think it does need some investigation https://github.com/UniversalMediaServer/api/actions/runs/4514708897/jobs/7951119877

It seems different to what that user is experiencing @Mik-S-UMS since this still returns a result, but the result is in the wrong language.

**Comment by Mik-S-UMS** [comment]
It was a long shot as I'm guessing what was causing their problems with receiving metadata, it mostly appears to be the German videos that are effected but not exclusively.

Could you have a closer look when you can?

**Comment by SubJunk** [comment]
Yes I can look into it, can you help by checking if any of those failed German results exist on https://www.themoviedb.org/ ?

**Comment by Mik-S-UMS** [comment]
I tried a few of them on there and do exist on TMDB.

[Die Goldfische](https://www.themoviedb.org/movie/535092-plan-a)
[Der beste Film aller Zeiten](https://www.themoviedb.org/movie/668640-competencia-oficial)
[Das Licht, aus dem die Träume sind](https://www.themoviedb.org/movie/821494-the-last-film-show)
[Der See der wilden Gänse](https://www.themoviedb.org/movie/575428)
[Immer Drama um Tamara](https://www.themoviedb.org/movie/38961-tamara-drewe)

From what I can tell they are originally from different languages (English, Chinese, Indian etc) but are found with the German names on TMDB easily enough.

One that I would expect to definitely get results is "Everything Everywhere All at Once" but for some reason is unable to.

**Comment by Mik-S-UMS** [comment]
It appears to mostly happen from their own rips of blurays or from downloads from tv mediathek.
I noticed that a filesize is required when making a request to the API so this may be why no match is found.
Is that needed to get metadata or is just the osdbHash enough?

**Comment by SubJunk** [comment]
This seems fixed now, both problems
