### ISSUE TITLE
Allow use of the private OMDb server

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#135]
@js-kyle Since we are using your fork of `imdb-api` and the owner doesn't seem to be paying attention to the things we have contributed, I suggest we add the support for private.omdbapi.com to your fork, what do you think?
It would be ideal to be able to pass that option as a parameter

**Comment by js-kyle** [comment]
Yeah that could be good, we could just maintain a fork under UMS org and have it publishing to npm master pushes?

**Comment by SubJunk** [comment]
Sounds good to me, are you keen to do that?

**Comment by js-kyle** [comment]
Yup, can you fork it into the org? Unsure if i can do that

**Comment by js-kyle** [comment]
Then i can apply my change as well as this one

**Comment by SubJunk** [comment]
fork done
