### ISSUE TITLE
Choose most appropriate result in movie searches

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#189]
This is less important now that we also search by year, but in rare cases two movies with similar names may be released in the same year, so we could address the TODO at https://github.com/UniversalMediaServer/api/blob/master/src/controllers/media.ts#L74 by doing a Jaro-Winkler comparison to pick the closest result instead of just the first one

**Comment by js-kyle** [comment]
Not sure how to approach this one. This is what I get for the following title search to our API

POST `/api/media/title` `{"title": "Black Rain", "year": "1989"}`

I get the following search results:

```
[
  SearchResult {
    title: 'Black Rain',
    year: 1989,
    imdbid: 'tt0096933',
    type: 'movie',
    poster: 'https://m.media-amazon.com/images/M/MV5BYTkwMDA2MmQtODI1MS00MGI5LWE5YTktMTUzYzY4ZDZjMmQ3XkEyXkFqcGdeQXVyMjY3MjUzNDk@._V1_SX300.jpg',
    name: 'Black Rain'
  },
  SearchResult {
    title: 'Black Rain',
    year: 1989,
    imdbid: 'tt0097694',
    type: 'movie',
    poster: 'https://m.media-amazon.com/images/M/MV5BYTMwMDBmMTgtZTNhMC00OTM4LTliMTEtODAyY2RlZTA5YjYxXkEyXkFqcGdeQXVyMTIyNzY1NzM@._V1_SX300.jpg',
    name: 'Black Rain'
  }
]
```

Which is correctly returning https://www.imdb.com/title/tt0097694/ and https://www.imdb.com/title/tt0096933/.

I'm unsure how Jaro-Winkler comparison would help us here

**Comment by SubJunk** [comment]
Yeah it wouldn't when the names are identical, just similar. Like if you searched for "Black Rain" and received "Black Rains", "Black: Rain" and "Black Rain Part II", or something
