### ISSUE TITLE
Validate hash results with season, episode number or year

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#190]
Due to OpenSubtitles API sometimes sending incorrect data, if we search for it based on the hash and it finds a result, the client will receive the wrong result, whereas in that situation we should mark it as a failed lookup in case the result is changed in the future on the OpenSubtitles server.

Movies can be validated by year, and episodes can be validated by season and episode number.

Currently the client also validates for it but we need to as well to prevent our database having incorrect results stored

**Comment by js-kyle** [comment]
Do you mean that we should validate the Open Subs response against the OMDb one?

**Comment by SubJunk** [comment]
I mean the client passes those in
