### ISSUE TITLE
Correct HTTP semantics

### ISSUE THREAD

**Issue by js-kyle** [UniversalMediaServer/api#205]
Before the first release I'm  keen to fix this, I don't think they are right at the moment.

E.g. I think all endpoints should be GET endpoints as they retrieve data not create it. Anything passed to the endpoint should be in URL query parameters opposed to request bodies, as GET request bodies are not meant to be used to modify the response

Does that sound good

**Comment by SubJunk** [comment]
Yup sounds good to me
