### ISSUE TITLE
No results for titles when we don't provide an apostrophe

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#276]
For example https://www.omdbapi.com/?t=Lemony%20Snickets&apikey=foo does not work but https://www.omdbapi.com/?t=Lemony%20Snicket%27s&apikey=foo does work
I have contacted the developer via Patreon and will post any updates here

**Comment by valib** [comment]
@SubJunk both URI you provided doesn't work.

**Comment by valib** [comment]
Sorry my error.

**Comment by SubJunk** [comment]
No problem. If you are interested I can provide you an API key to use, but I can't post it on GitHub

**Comment by SubJunk** [comment]
I got an update from the developer of OMDb who says he is working on a fix and will update me when it's done

**Comment by SubJunk** [comment]
This seems to be fixed
