### ISSUE TITLE
Support searching by metadata

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#32]
The UMS client currently looks for a match to the OS hash, and if that fails it looks for a metadata match based on a sanitised title. We should allow that to happen through our API too.

**Comment by js-kyle** [comment]
@SubJunk I've made a start on this, there's an open WIP PR.

Can you confirm what you mean by sanitized title? Or does the client do the santizing so we don't worry about it here

**Comment by js-kyle** [comment]
Bump

**Comment by SubJunk** [comment]
The client does the sanitizing but we could decide where that would best live. It might be better to pass the whole filename through to the API and have that sanitize... Though maybe it's better for user privacy to have the client do it so they aren't sending the filename over the net. Thoughts?

**Comment by SubJunk** [comment]
This is the way we currently do it https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/java/net/pms/util/OpenSubtitle.java#L1871
So it's using `SearchSubtitles` and passing a `query` parameter

**Comment by js-kyle** [comment]
Ah cool that's good context thanks. I think UMS server should keep doing that bit then

**Comment by js-kyle** [comment]
@SubJunk I'm getting somewhere with this, do you have an example filename which should return data?

**Comment by SubJunk** [comment]
Maybe like `Homeland S02E05`

**Comment by js-kyle** [comment]
Done!
