### ISSUE TITLE
Don't create failure document for external API errors

### ISSUE THREAD

**Issue by js-kyle** [UniversalMediaServer/api#386]
At the moment, if the omdb api returns an unauthorized response, such as providing no API key, we should not create a `failed_lookups` document which prevents the metadata being found when the issue is resolved

**Comment by SubJunk** [comment]
@js-kyle does this definitely happen? I thought we would be throwing an error at the time of lookup so it wouldn't have a chance to create the failed lookup document?

**Comment by js-kyle** [comment]
Yeah it didn't seem correct at the time, and I can't reproduce.. will close
