### ISSUE TITLE
Episode lookups failing

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#406]
I'm not sure why but we are still getting some failed episode lookups after v2 when we shouldn't. For example:

https://www.universalmediaserver.com/api/media/v2/title?title=Homeland&season=1&episode=1

fails but that is available at https://www.omdbapi.com/?t=Homeland&plot=full&r=json&season=1&episode=1

**Comment by SubJunk** [comment]
There also seems to be nothing wrong with the season lookup we use https://www.omdbapi.com/?i=tt1796960&plot=full&r=json&season=1

**Comment by js-kyle** [comment]
This works for me at https://www.universalmediaserver.com/api/media/v2/title?title=Homeland&seasonNumber=1&episodeNumber=1

**Comment by SubJunk** [comment]
Fixed in https://github.com/UniversalMediaServer/api/commit/03082349d9a0a350251e5f50c6cc6a8f011823e5
