### ISSUE TITLE
CI should run tsc

### ISSUE THREAD

**Issue by js-kyle** [UniversalMediaServer/api#430]
It has tripped me up before that as our TypeScript is compiled in memory for tests, sometimes it looks like tests fail, but it is just due to a TypeScript error that the app isn't starting.

e.g. this build https://github.com/UniversalMediaServer/api/runs/1907542809?check_suite_focus=true

It would be run clearer if we ran tsc as a pre step to the tests

**Comment by SubJunk** [comment]
Ah yep good catch.
