### ISSUE TITLE
Catch errors we throw

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#441]
There is a bug where if we throw errors in `getFromIMDbAPIV2` for example, we don't catch the errors which means a failure document doesn't get created

May have been fixed in the monoendpoint but not in media/v1 and v2

**Comment by SubJunk** [comment]
So I did an implementation of this but I wonder if it would be better to create a more general approach - instead of just creating the failure documents specifically there, maybe we should put that at a high level so that if any error happens that isn't an OpenSubs outage, it creates a failure document.

Thoughts @js-kyle ?

**Comment by js-kyle** [comment]
Yeah i think we should try to generalise the failures as that code is littered in so many place at the moment

**Comment by SubJunk** [comment]
Ok, I'll work on that in the same branch
