### ISSUE TITLE
Media Library TV Show Metadata

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#477]
Moved from https://github.com/UniversalMediaServer/UniversalMediaServer/issues/2441

Hi There,

Firstly great work on this project!

I've an issue that started since 10.2 which is that the API TV Show search isn't selecting the correct TV show. My file names are 'ShowName S01E01 EpisodeName.ext'
[ums_dbg_2021-03-23-09-56.zip](https://github.com/UniversalMediaServer/api/files/6192536/ums_dbg_2021-03-23-09-56.zip)
and I have used MetaX to update the files metadata but for these series the IMDB data is pointing to either an older series of the same name or a short film of the same name. I've tired adding the series year to the end of the file name or after the series name without success.

The affected series are Black Mirror, Grimm, The Flash 2014 series and the Tick 2016 series - there could be more but these are the ones I'm affected by.

The 10.1 release was the best API correctly getting then IMDB data for both Movies and TV Shows.

Many thanks
Steve

**Comment by js-kyle** [comment]
The seriestitle can be more accurate by using the imdbID when passed to it, so I've made that change to the endpoint.

For the cases in this logfile, as the year is unknown, it is hard to get accurate examples, but as we know the imdbID, they could be

**Comment by SubJunk** [comment]
@js-kyle just a thought, maybe when we have no year for the TV series, instead of returning the earliest one, we should return the most popular one based on the vote count?

Also in the case of Black Mirror I could only see one TV series with that title, so what result are we currently returning? https://www.imdb.com/find?q=Black%20Mirror&s=tt&ref_=fn_al_tt_mr

**Comment by Mik-S-UMS** [comment]
@SubJunk I think the way IMDB is labelling Black mirror could be the issue in this case. There are currently 5 series and 2 specials. IMDB seems to be showing the year that series came out, probably because they are more like standalone specials than a normal series. 

I think Movian gets it's metadata from www.themoviedb.org, maybe thats worth a look instead of IMDB https://www.themoviedb.org/tv/42009-black-mirror/seasons

**Comment by js-kyle** [comment]
@SubJunk at the moment https://api.universalmediaserver.com/api/media/seriestitle?title=Black%20Mirror returns data for https://www.imdb.com/title/tt10314544/

Ill try to look into the popularity enhancement

**Comment by SubJunk** [comment]
Is it possible we have a bug that would cause us to store a non-series with `type: series`?
Because if I go to OMDb directly with http://www.omdbapi.com/?t=black+mirror&y=2019, it is returning that as a movie:

```
{"Title":"Black Mirror","Year":"2019","Rated":"N/A","Released":"N/A","Runtime":"N/A","Genre":"Short, Music","Director":"Kingsley Egei","Writer":"Kingsley Egei","Actors":"Kingsley Egei, Jordan Diomande, Sarah Enstad, Jabari Everett","Plot":"The Directorial debut of Kingsley Egei as he creates a dark, humble, and aggressive music video to the song Black Mirror By SXTWLVE.","Language":"English","Country":"USA","Awards":"1 nomination.","Poster":"https://m.media-amazon.com/images/M/MV5BMzhhMjE0YTUtMjBmMS00NTcxLTljN2MtMTBmM2RkOTcyMWE5XkEyXkFqcGdeQXVyNzQ5MTUxNDU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.2/10"}],"Metascore":"N/A","imdbRating":"6.2","imdbVotes":"5","imdbID":"tt10314544","Type":"movie","DVD":"N/A","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True"}
```

**Comment by SubJunk** [comment]
This is fixed now
