### ISSUE TITLE
Way to let client know to invalidate cache

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#480]
There are some times where we fix a bug in the API or improve the hit rate so much that it would be best for the client to forget its "successful" information and get it fresh.
I am thinking of having an endpoint that the client can hit which will store the latest sub-versions of endpoints.

So with this idea, we have an endpoint like `/api/versions` that returns a payload like:

```
{
  '/api/media/seriestitle': 2,
  '/api/media/video': 3
}
```

and we also return a `version` parameter with each normal request, so that the client stores which (sub)version of the endpoint it received its data from.

On startup, or at an interval, the client hits this new endpoint and searches its local database for any TV series records that are not version 2, and any video records that are not version 3, and loops through any results and looks up the fresh data, updating the version as well.

A use case is like with the incorrect series lookups bug we are fixing, it would have been nice to have this feature so we could instruct the client to forget its stored series after deploying that fix, but we have no way to do that right now.

Open to other approaches @js-kyle

**Comment by js-kyle** [comment]
Agree on the feature, would be very helpful. Just trying to thing of the nicest implementation, but I haven't thought of other ideas yet other than your one

**Comment by js-kyle** [comment]
I can work on API side of this if you want to look at implementing the client side

**Comment by SubJunk** [comment]
Sweet, will let you know when I do that

**Comment by SubJunk** [comment]
This is done
