### ISSUE TITLE
Fix support for esm modules

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#550]
Getting persistent build failures, I have a branch where I fixed that but now Jest doesn't like it so it needs more work https://github.com/UniversalMediaServer/api/compare/fix-tsc

@js-kyle any ideas?

**Comment by js-kyle** [comment]
Some deps have updated to esm modules so we need to make changes based on that

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by js-kyle** [comment]
I think it might be easier to rollback `escape-string-regexp` to v4 without the esm module change, and then address what we need to do in order for us to upgrade to full esm. There may be a few hurdles with out use of Jest and ts-node by the looks of it
