### ISSUE TITLE
Get movie and episode ratings

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#63]
This one is potentially tricky so I made a separate story. Most of our information never changes except to start existing, but ratings are changeable, do we care? It's probably pretty low stakes, so one option is to not really care about it. Another option is to periodically update it in a similar way to how we check for missing lookups.

Thoughts @js-kyle ?

**Comment by js-kyle** [comment]
@SubJunk I think for purpose we could use MongoDB ttl, so each metadata record expire say after 1 month, then is refreshed with the latest data.

We could also use that approach for the failed lookups too, rather than the API having logic to check if the failed lookup is x days old

**Comment by SubJunk** [comment]
Keen for that

**Comment by js-kyle** [comment]
This has been done (using the ttl approach)
