### ISSUE TITLE
Think about API versioning

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#65]
Old clients should continue to work forever, so we need a way to identify which version of the API the client was designed to consume

**Comment by js-kyle** [comment]
Does the UMS client set a user agent header?

**Comment by js-kyle** [comment]
Or perhaps we can just set a custom header to avoid url versioning

**Comment by SubJunk** [comment]
Yeah we can do that

**Comment by SubJunk** [comment]
This can be done when it's needed
