### ISSUE TITLE
Pre-cache all episodes for a series

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#71]
See https://github.com/UniversalMediaServer/api/pull/70/files#r392632619

**Comment by js-kyle** [comment]
I have an idea for this one, so I would probably pick it up in the next day or so unless someone beats me to it

**Comment by js-kyle** [comment]
My plan was to use `worker_threads` but that had some limitations I wasn't expecting.

Commit is stored here https://github.com/UniversalMediaServer/api/commit/5702642e6877c654f3faf0d625003f0460fb719a

**Comment by js-kyle** [comment]
https://github.com/UniversalMediaServer/api/pull/77
