### ISSUE TITLE
Don't expire good records

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#84]
Happy to discuss this but I think it would be good to remove the document expiry on MediaMetadata. I know it makes it convenient for progressively adding more fields but given that we are attempting to cache rate-limited services, it stops us from accumulating good results over time. Thoughts?

**Comment by js-kyle** [comment]
I guess it depends how we define a 'good' record. If we have some sort of baseline for that we could change

**Comment by SubJunk** [comment]
In this case I just mean anything that we currently put into MediaMetadata

**Comment by js-kyle** [comment]
It's a trade off between more caching vs less rich data, unsure what is more important

Currently, some endpoints return the imdbapi data and others use Open Subtitles if it is able to create the document based on just that response.

Maybe, we could change it so all endpoints will call both services and make the best data possible before it creates the document, then remove the ttl?

**Comment by SubJunk** [comment]
Yep I'm keen. The only endpoint that can't do it is when looking up via OpenSubtitles hash but the client follows that up with a title search anyway
