### ISSUE TITLE
Return different results for temporary failures vs. real failures

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/api#85]
We need to make sure that we are returning a different error/message depending on whether a lookup has failed due to a real failure to find it (both APIs returned no results, or the results were not complete enough), or just a temporary failure e.g. high server load from the third parties.
We should also make sure that those temporary failures don't result in a FailedLookup being written, since in those cases it would be better to try until a real result is received, even if that result is just that they don't have that record.

We may already do some of this so this story involves some review too.

**Comment by js-kyle** [comment]
done
