### ISSUE TITLE
Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by js-kyle** [UniversalMediaServer/api#90]
https://www.universalmediaserver.com/api/media/a04cfbeafc4af7eb/884419440

```
TypeError: Cannot read property 'match' of undefined
    at LibID.extend (/Users/kyle-dev/umsapi/node_modules/opensubtitles-api/lib/identify.js:71:36)
    at /Users/kyle-dev/umsapi/node_modules/opensubtitles-api/index.js:209:42
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.exports.getByOsdbHash (/Users/kyle-dev/umsapi/src/controllers/media.ts:89:14)
    at /Users/kyle-dev/umsapi/src/routes/media.ts:7:3
    at bodyParser (/Users/kyle-dev/umsapi/node_modules/koa-bodyparser/index.js:95:5)
    at /Users/kyle-dev/umsapi/src/app.ts:35:3
    at /Users/kyle-dev/umsapi/src/app.ts:23:5

```

**Comment by js-kyle** [comment]
https://github.com/vankasteelj/opensubtitles-api/pull/52

**Comment by vankasteelj** [comment]
Hi, thanks for the PR!

**Comment by js-kyle** [comment]
@vankasteelj no problem, thanks for the nice module!

**Comment by SubJunk** [comment]
@vankasteelj could you please release the fix to npm?

**Comment by vankasteelj** [comment]
5.1.1 should be available

**Comment by SubJunk** [comment]
@vankasteelj thanks! :)

**Comment by SubJunk** [comment]
@js-kyle it looks like bumping to that version causes a test failure for us so we will likely need to manually do the bump instead of dependabot

**Comment by js-kyle** [comment]
It's a genuine test failure rather than a Dependabot issue as I saw a similar thing yesterday when I manually bumped it to reference Github master branch for that module. I can look at it again

**Comment by js-kyle** [comment]
I submitted a new PR to the module, as my last change seemed to break other cases which should still work.

https://github.com/vankasteelj/opensubtitles-api/pull/53

Our tests pass when using my fix, as well as stopping the error in this issue
