### ISSUE TITLE
Install Dependabot rather than Depshield

### ISSUE THREAD

**Issue by js-kyle** [UniversalMediaServer/api#92]

**Comment by SubJunk** [comment]
@js-kyle It's installed, is there anything we can do to stop depshield now? Or will it just stop?

**Comment by js-kyle** [comment]
Depshield is a third party thing which must have been installed at some point, maybe to the UMS org? It is third party not a native github thing

If it is used elsewhere you should be able to just remove it from this project here https://github.com/apps/sonatype-depshield

**Comment by SubJunk** [comment]
Sweet I've disabled it for this repo
